# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02be80e1b8bea77e41d99a4796be5af26741771b4ec5d3198dc2860486f4dad86a7bc4b1609c20fcce5dd1794802fe115434826c653a31e7da6307a763399c25

test:
  secret_key_base: 385c7564a931c1042adc6e1f585002a89ee1966b883e322d2cc4ad74de57f0d894404431b08e69179c792e1b9088e84bf6dbb9988228b0c2e32f6eefe535494a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
